version: 2.1
orbs:
  # use Cypress orb from CircleCI registry
  cypress: cypress-io/cypress@1.0.1
workflows:
  build:
    jobs:
      # checks out code and installs dependencies once
      - cypress/install:
          # and builds the app using this command
          build: 'yarn install'

      - cypress/run:
          name: '2 machines using Chrome'
          # job will use workspace with code and dependencies
          # installed by the "install" job
          requires:
            - cypress/install
          # use executor with Chrome installed
          executor: cypress/browsers-chrome69
          # use browser "chrome" for running tests
          browser: chrome
          record: true
          parallel: true
          parallelism: 2
          group: '2x-chrome'
          start: 'npm start'
